apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
spec:
  selector:
    matchLabels:
      app: authservice
  replicas: 1
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: emreoytun/authservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-ssvc
spec:
  selector:
    app: authservice
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8086
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authservice-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: ""  # Leave empty if not using a specific domain
      http:
        paths:
          - path: /authservice
            pathType: Prefix
            backend:
              service:
                name: authservice
                port:
                  number: 80
